### ISSUE TITLE
Feedback + Question.

### ISSUE THREAD

**Issue by iNiKKo** [GameTechDev/XeSSUnrealPlugin#6]
**EDIT : it does work but not when playing in View-port only in STANDALONE**

Hello, i have tested the new UE 5.3.0 support and it works.
but i am either doing this wrong or it doesn't work for me, i have followed the PDF example, which made the combo box work but it wouldn't actually affect the game.

here in this image : i am guessing something as simple as this should change the Quality mode ? but it doesn't
![image](https://github.com/GameTechDev/XeSSUnrealPlugin/assets/67593147/af3c8c46-cdd5-4aad-980b-2076232cae4d)

on the right is the solution i am currently using to make XeSS work.
if i am doing something wrong could you post a picture with the correct way to make it work? and if so also update the PDF for next update.

**Comment by iNiKKo** [comment]
EDIT : it does work but not when playing in View-port only in STANDALONE

**Comment by xessgamedev** [comment]
Sorry to respond late.
Yes, Play-In-Editor is different from play in standalone mode, and somehow more complicated, because plugin lost control to resolution factor via API since Unreal 5.0. Plugin has to use `r.ScreenPercentage` to make it work. In order to make `r.ScreenPercentage` to work in Play-In-Editor mode, additional configuration required.
If any further question, please just let us know. 

Feedback here is always welcome.
